# Generated by Django 3.2.3 on 2021-06-13 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=10)),
                ('interest_spot', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=64)),
                ('area_name', models.CharField(max_length=64)),
                ('link', models.URLField(null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('spot_name', models.ForeignKey(db_column='spot_name', on_delete=django.db.models.deletion.CASCADE, to='online_travel.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('spot_name', models.ForeignKey(db_column='spot_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='online_travel.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Livechat',
            fields=[
                ('ip', models.IntegerField(primary_key=True, serialize=False)),
                ('access', models.BooleanField()),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_travel.member')),
            ],
        ),
        migrations.CreateModel(
            name='Img_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_2', models.TextField(null=True)),
                ('img_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_travel.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=128, null=True)),
                ('spot_name', models.ForeignKey(db_column='spot_name', on_delete=django.db.models.deletion.CASCADE, to='online_travel.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
