# Generated by Django 3.1.3 on 2021-05-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=10)),
                ('interest_spot', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=64)),
                ('area_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, null=True)),
                ('spot_name', models.ForeignKey(db_column='spot_name', on_delete=django.db.models.deletion.CASCADE, to='online_travel.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Livechat',
            fields=[
                ('ip', models.IntegerField(primary_key=True, serialize=False)),
                ('access', models.BooleanField()),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_travel.member')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=128, null=True)),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_travel.member')),
                ('spot_name', models.ForeignKey(db_column='spot_name', on_delete=django.db.models.deletion.CASCADE, to='online_travel.spot')),
            ],
        ),
    ]
