# Generated by Django 3.1.3 on 2021-06-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
