# Generated by Django 3.1.3 on 2021-06-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_travel', '0003_auto_20210606_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
