# Generated by Django 3.1.3 on 2021-06-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_travel', '0003_auto_20210606_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('spot_name', models.ForeignKey(db_column='spot_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='online_travel.spot')),
            ],
        ),
    ]
