# Generated by Django 3.1.3 on 2021-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_travel', '0004_auto_20210612_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='explanation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
